### ISSUE TITLE
Use groupedbar as a seriestype

### ISSUE THREAD

**Issue by pearlzli** [JuliaPlots/StatPlots.jl#106]
I'd like to use `groupedbar` in a plot recipe of my own. However, when I set `seriestype := :groupedbar`, I get the following error:
```julia
ERROR: The backend must not support the series type Val{:groupedbar}, and there isn't a series recipe defined.
Stacktrace:
 [1] apply_recipe(::Dict{Symbol,Any}, ::Type{Val{:groupedbar}}, ::UnitRange{Int64}, ::Array{Float64,1}, ::Void) at /home/rcepxl10/.julia/v0.6/RecipesBase/src/RecipesBase.jl:287
 [2] _process_seriesrecipe(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}) at /home/rcepxl10/.julia/v0.6/Plots/src/pipeline.jl:406
 [3] _plot!(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Tuple{Shockdec}) at /home/rcepxl10/.julia/v0.6/Plots/src/plot.jl:231
 [4] #shockdec#155(::Array{Any,1}, ::Function) at /home/rcepxl10/.julia/v0.6/RecipesBase/src/RecipesBase.jl:363
 [5] shockdec() at /home/rcepxl10/.julia/v0.6/RecipesBase/src/RecipesBase.jl:363
```

As far as I can tell, the difference between `groupedbar` and other recipes defined in this package that can be successfully set as `seriestype`s (e.g. `marginalhist`, `violin`) is that it's defined using `@userplot` with the following function header (on master):
```julia
@recipe function f(g::GroupedBar)
```

Compare to `marginalhist`'s header, which uses `@shorthands` and takes as its first argument a `Type{Val{:marginalhist}}`:
```julia
@recipe function f(::Type{Val{:marginalhist}}, plt::AbstractPlot; density = false)
```

I spent a little time trying to modify `groupedbar` to take in a `Type{Val{:groupedbar}}` without much success, probably because I'm still trying to grasp how recipes work on the inside. Is this functionality (setting `seriestype := :groupedbar` in a recipe) currently possible? If not, can I put in a request for it to be added? Am I understanding the reason `groupedbar` currently can't be used as a `seriestype` correctly?

**Comment by mkborregaard** [comment]
`groupedbar` is a user recipe, not a series recipe. The reason is that each group is implemented as it's own series. series recipes are more convenient to use, but have more restrictions in what they can do - so we try to implement things as series recipes if we can, and implement the rest as user recipes. User recipes can do everything Plots can, but do for instance require the package defining the user recipe to be in scope when defining another recipes using it.

**Comment by mkborregaard** [comment]
Read more here http://docs.juliaplots.org/latest/recipes/

**Comment by mkborregaard** [comment]
Currently the only option is to depend on StatPlots and then return `GroupedBar((args...))` at the end of the user recipe passing to it.

**Comment by pearlzli** [comment]
Thanks! I think I missed the difference between user and series recipes partially because of the indentation of the bulleted list under "These are the dispatch signatures for each type" in the recipes documentation.

Could you elaborate a bit more on calling `GroupedBar((args...))` in a user recipe? I'm currently getting the following error:

```julia
julia> using RecipesBase, StatPlots

julia> @userplot MyPlot
myplot! (generic function with 1 method)

julia> @recipe function f(mp::MyPlot)
       @series begin
       StatPlots.GroupedBar(rand(5, 3))
       end
       end

julia> myplot()
ERROR: MethodError: no method matching grouped_xy(::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64)
Stacktrace:
 [1] macro expansion at /home/rcepxl10/.julia/v0.6/StatPlots/src/bar.jl:11 [inlined]
 [2] apply_recipe(::Dict{Symbol,Any}, ::StatPlots.GroupedBar) at /home/rcepxl10/.julia/v0.6/RecipesBase/src/RecipesBase.jl:287
 [3] _process_userrecipes(::Plots.Plot{Plots.PlotlyBackend}, ::Dict{Symbol,Any}, ::Tuple{MyPlot}) at /home/rcepxl10/.julia/v0.6/Plots/src/pipeline.jl:81
 [4] _plot!(::Plots.Plot{Plots.PlotlyBackend}, ::Dict{Symbol,Any}, ::Tuple{MyPlot}) at /home/rcepxl10/.julia/v0.6/Plots/src/plot.jl:175
 [5] #myplot#1(::Array{Any,1}, ::Function) at /home/rcepxl10/.julia/v0.6/RecipesBase/src/RecipesBase.jl:363
 [6] myplot() at /home/rcepxl10/.julia/v0.6/RecipesBase/src/RecipesBase.jl:363
```

**Comment by piever** [comment]
`GroupedBar((args...))` means that the arguments have to be enclosed in a Tuple. In your case:

```
julia> @recipe function f(mp::MyPlot)
       @series begin
       StatPlots.GroupedBar((rand(5, 3),))
       end
       end
```

Back to the main point of discussion, it is a bit unfortunate that to have a GroupedBar in a recipe one has to depend on StatPlots (which is relatively heavyweight) but I'm not sure of what would be a good refactoring that would solve this issue...

**Comment by mkborregaard** [comment]
(you don't need the series block here `@recipe f(mp::MyPlot) = GroupedBar((rand(5,3),))`)

**Comment by mkborregaard** [comment]
@pearlzli what's your recipe?

**Comment by pearlzli** [comment]
@piever Got it, thanks!

@mkborregaard The recipe I have in mind is basically a grouped bar plot overlaid with a line. I did get it to work in the end.

**Comment by mkborregaard** [comment]
Sounds great. You're welcome to ask again if you need help.
