### ISSUE TITLE
@df : passing a symbol through a variable throws an error

### ISSUE THREAD

**Issue by romainFr** [JuliaPlots/StatPlots.jl#119]
This is probably just me not understanding something very simple about how Symbols are passed, but

```julia
using StatPlots, DataFrames
smallDf = DataFrame(A = rand(10),B=rand(10))
x = :A
@df smallDf histogram(x)
```
Throws 
```julia
ERROR: ArgumentError: invalid index: Union{}[]
Stacktrace:
 [1] #create_columns_from_iterabletable#1(::TableTraitsUtils.#_default_array_factory, ::Function, ::DataFrames.DataFrame, ::Array{Union{},1}) at /localhome/romain/.julia/v0.6/TableTraitsUtils/src/TableTraitsUtils.jl:142
 [2] extract_columns_from_iterabletable(::DataFrames.DataFrame) at /localhome/romain/.julia/v0.6/StatPlots/src/df.jl:100
```

Whereas ```@df smallDf histogram(:A)``` or  ```smallDf[x]``` work as I would expect. 
This is with the latest master (also on the latest release) and julia 0.6.1.

**Comment by piever** [comment]
What is missing is that macro are called before the code is executed, so the macro cannot know that `x` will be a symbol. `@df` is inspired by DataFramesMeta's `@with` (see [here](https://github.com/JuliaStats/DataFramesMeta.jl#with)) and distinguishes symbols syntactically and cannot know that `x` will be a symbol at parse time. If you think this application is common enough, I can maybe implement the `_I_(expr)` notation (as they do in `@with`). like:

```julia
x = :A
@df smallDf histogram(_I_(x))
```
But honestly I'm not a huge fan of this syntax. Maybe:

```julia
x = :A
@df smallDf histogram($x)
```

would make more sense? It seems more intuitive to me, not sure why DataFramesMeta went with `_I_(expr)` which is a bit awkward to type.

**Comment by romainFr** [comment]
Thanks ! Of course that makes sense. I encountered it while changing some old code that was using the deprecated syntax  ```plot(smallDf,x)```. I think that might be a nice feature to add if more people agree -- as for the syntax, I guess being coherent with ```DataFrameMeta``` is a good thing.

**Comment by piever** [comment]
@mkborregaard what's your take for a syntax that allows "interpolating" symbols in a `@df` call? `_I_(expr)` like DataFramesMeta, `$expr` (which is what I would try as a user) or yet another thing?

**Comment by mkborregaard** [comment]
I like the interpolation, I don't think we need consistency with DataFramesMeta on this.

**Comment by piever** [comment]
I actually started wondering whether we should just always use `cols` instead. Now we have `cols(v::AbstractArray{Int64})` mean the `hcat` of those columns, but maybe we could also have `cols(v::AbstractArray{Symbol})` to select the columns by name, as well as a `cols(v::Int64)` or `cols(v::Symbol)` if it's just one column but we want to choose it by index rather than name, or we want to chose it by name but the name is a variable. Maybe the 1 column version could be renamed `col` but I find it more Julian to have one function with several methods.

The rule would be:

- If it's a symol that you type, use the symbol
- otherwise, use `cols` to signal to the macro that the content represent one or more columns

**Comment by mkborregaard** [comment]
I think that suggestion has the advantage that the interpolation after a macro feels a little magical, and enough slightly differing uses of `$` after a macro (i.e. the suggested use is different from that used in BenchmarkTools) could create slightly fuzzy interface. Though cols is clearly ours, and at the cost of being slightly clumsy and wordy should be quite clear to understand.

**Comment by piever** [comment]
@romainFr If you want you can try #120 and see if it addresses your use case.

**Comment by romainFr** [comment]
@piever It does, thanks !
