### ISSUE TITLE
Title position for corrplot

### ISSUE THREAD

**Issue by Msturroc** [JuliaPlots/StatPlots.jl#141]
The corrplot recipe doesn't allow for any position other than a central one currently. All these commands produce the same output

`corrplot(rand(100,4),title="(A)",title_loc=:left)`

`corrplot(rand(100,4),title="(A)",title_loc=:centre)`

`corrplot(rand(100,4),title="(A)",title_loc=:right)`

**Comment by mkborregaard** [comment]
Is this on all backends?

**Comment by Msturroc** [comment]
I have just tried plotly(), pyplot() and gr(). No luck on any of them

**Comment by daschw** [comment]
> Is this on all backends?

Yes, it's in the recipe. Depending on the size of the input matrix a "proper" central subplot in the first row is chosen to hold the title in https://github.com/JuliaPlots/StatPlots.jl/blob/master/src/corrplot.jl#L68-L70.
I propose also checking for `title_location` in the recipe and changing these lines accordingly to choose the right subplot.

**Comment by mkborregaard** [comment]
good idea
