### ISSUE TITLE
Subplots for density plots using StatPlots

### ISSUE THREAD

**Issue by gdoshi9** [JuliaPlots/StatPlots.jl#144]
Hi,
I am using `StatPlots` to create density plots for my data. Specifically I am using `@df` syntax with the backend of `Plotly`. Example:
```
@df school density(:MAch, group = (:Sx, :Sector), legend = :topleft)
```
I am wondering if there is some way to add a subplot with this syntax under the `Plotly` environment? I tried using the usual subplot technique of `Plotly`, but that doesn't seem to work here.

**Comment by mkborregaard** [comment]
You can't use plotly commands in Plots, even using the plotly backend. You can add a subplot with Plots using the syntax described here: http://docs.juliaplots.org/latest/layouts/#advanced-layouts
