### ISSUE TITLE
Groupedbar not ploting anything

### ISSUE THREAD

**Issue by muriloasouza** [JuliaPlots/StatPlots.jl#151]
Hello i'm having an issue using Groupedbar. Essentially, this is my code.

```
workspace()

using StatPlots

Dbefore = [0.2410; 4.6709; 4.7775; 4.9210; 4.9397; 5.0426; 5.0677; 5.2084; 5.2080; 4.7775; 5.8069; 6.3106; 6.3101; 7.5012; 7.9857;8.3787; 8.3786];
Dafter = [0.1192; 2.3108; 2.4009; 2.4932; 2.4922; 2.4441; 2.4702; 2.6176; 2.6173; 2.4009; 2.8985; 3.1818; 3.1925; 4.2242; 4.6714; 5.0027; 5.0027];

groupedbar([Dbefore Dafter], bar_position = :dodge, bar_width=0.7)
```

I'm using Atom/Juno. Everything runs fine, but the graphic isn't being ploted in the Plots Tab.

**Comment by piever** [comment]
As I mentioned on the [discourse thread](https://discourse.julialang.org/t/error-using-statplots/12500/2?u=piever), on Julia master `workspace()` is discontinued:

```julia
julia> workspace()
ERROR: `workspace()` is discontinued, consider Revise.jl for an alternative workflow.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] workspace() at ./deprecated.jl:1126
 [3] top-level scope at none:0
```

and it was always problematic and never worked well with Plots. I'm not sure how to fix this but I would simply recommend to avoid using `workspace`.

**Comment by muriloasouza** [comment]
Yes, sorry. I forgot to remove that.

After i did some update packages ("ink" to 0.9.1, julia-client to 0.7.1 and some other), i stoped getting errors while using both `workspace()` and `using StatPlots`.

I have removed the `workspace()` command, but the graphic still isn't being ploted.

**Comment by piever** [comment]
I'm not sure what may be going on. If you try simply opening Juno and evaluating:

```julia
using Plots
gr()
display(plot(rand(10)))
```

does that work (in that case you're probably simply missing a call to `display` to actually display the plot).

If that doesn't work I'm not sure how to help, you may have better luck in the asking for help on the Juno side (either with an issue or in the [chat](https://gitter.im/JunoLab/Juno)).

**Comment by muriloasouza** [comment]
That fixed it! The `display` command.

Thanks a lot piever!
