### ISSUE TITLE
isnull not defined

### ISSUE THREAD

**Issue by jstrube** [JuliaPlots/StatPlots.jl#185]
Can I ask why #183 was reverted?
I'm getting errors related to `isnull not defined`. With the `(el === nothing)` test instead of `isnull`, I'm getting no errors.

**Comment by piever** [comment]
It was not the proper fix, meaning it would fail in case some of your data was missing. This should be fixed on master anyway. Can you `] update` and try again?

**Comment by jstrube** [comment]
looks good from here!
Thanks for the quick fix.
