### ISSUE TITLE
A way to provide group labels for groupbar?

### ISSUE THREAD

**Issue by maximsch2** [JuliaPlots/StatPlots.jl#21]
Is there a way to provide legend labels there separately? 

I've tried what I thought was a natural thing (supplying `labels=["label1", "label2"]`), but that doesn't work.

Going through docs for recepies and even looking at `SliceIt` recepie that seems to be called here didn't help, but I'll appreciate pointers.

**Comment by maximsch2** [comment]
Figured out that this works:
```julia
current().series_list[1].d[:label] = "label1"
```
but it will be great if groupedbar would work out of the box.

**Comment by tbreloff** [comment]
```julia
using StatPlots; groupedbar(rand(10,3), bar_position = :stack, bar_width=0.7, lab=["A" "B" "C"])
```

**Comment by maximsch2** [comment]
![image](https://cloud.githubusercontent.com/assets/464680/19542038/0e29dc70-9620-11e6-9acd-9337218d047f.png)
Doesn't seem to work....
