### ISSUE TITLE
cornerplot

### ISSUE THREAD

**Issue by tbreloff** [JuliaPlots/StatPlots.jl#3]
See: https://github.com/JuliaPlots/PlotRecipes.jl/issues/1#issuecomment-226729872

cc: @mauro3 (do you want to submit a PR?)

**Comment by mauro3** [comment]
Will do.

**Comment by mauro3** [comment]
Here the readme picture:
![cornerplot](https://cloud.githubusercontent.com/assets/4098145/16762241/f924c8ac-4823-11e6-8720-83025606b5e1.png)

**Comment by tbreloff** [comment]
i've been fixing this up.  new screenshots:

![tmp](https://cloud.githubusercontent.com/assets/933338/17787905/2e161b7c-6559-11e6-937a-20209301905b.png)

![tmp](https://cloud.githubusercontent.com/assets/933338/17787917/3af9b0e2-6559-11e6-8613-c177efb0b038.png)

**Comment by mauro3** [comment]
Cool! 

One thing which would be nice to have at some point is the have combined contour-hist-scatter plots, like so: http://corner.readthedocs.io/en/latest/pages/quickstart.html

**Comment by tbreloff** [comment]
Can't you do that already with corrplot? (Well, not with "compact")

**Comment by mauro3** [comment]
I mean this plot:
![p](https://cloud.githubusercontent.com/assets/4098145/17809692/ae02a62e-6618-11e6-9c36-7cc406893a02.png)
How would you do that?

**Comment by tbreloff** [comment]
I guess I don't understand what it is. Is it a partial hist2d, but the
individual points are drawn when there's only a few?  And a contour
overlayed?  Certainly possible but might be slightly annoying to make.
You'd want to draw the hist2d as shapes I think. So the recipe would make 3
series... a shape, a scatter, and a contour.

**Comment by mauro3** [comment]
(I don't care about the histogram.)  But the contours are good as the scatter-plot is too dense in the middle to discern anything.  Anyways, just an idea for sometime-in-the-future work...

**Comment by tbreloff** [comment]
Oh. Then that would be pretty straightforward

**Comment by mauro3** [comment]
I'll ping you when I need/want it!

**Comment by mauro3** [comment]
I think it would be good to have x/y-tick labels along the top and left too.  With many variables it gets tricky to see where histograms are.

**Comment by mauro3** [comment]
Also using the `title` keyword sets a title on all subplots.
