### ISSUE TITLE
Add support to TimeSeries

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/StatPlots.jl#37]
Does the package support TimeSeries? The code below produces an error.

```julia
using TimeSeries
using StatPlots

dates  = collect(Date(1999,1,1):Date(2000,12,31))
series = TimeArray(dates, rand(length(dates)))

plot(series)
```

**Comment by mkborregaard** [comment]
No, but it should be straightforward to make a Type recipe that replaces a `TimeArray` with an `Array{DataTime}` object (which is accepted by Plots). You can see how to do this here: https://juliaplots.github.io/recipes/

**Comment by juliohm** [comment]
Thank you @mkborregaard, I am gonna read the docs for Plots recipes.

**Comment by milktrader** [comment]
@juliohm if you get a working recipe example I'd love to add it to the TimeSeries docs.

**Comment by mkborregaard** [comment]
@milktrader You might even consider adding it to the package itself? The idea of recipes is to be able to add plotting capability in the lightest way possible, so a Type recipe requires no dependency on Plots.jl – only on RecipesBase, which is a single macro. I personally think it is an elegant solution to the issue of adding generalized plotting capability to packages in a package ecosystem with multiple plotting packages.

**Comment by juliohm** [comment]
@mkborregaard thank you for sharing this idea, it is super useful. So basically, we can add plotting capabalities as recipes in any package without depending on the plot packages/backends. I will read `RecipesBase.jl` to implement visualization in my packages.

**Comment by pkofod** [comment]
Yes that is exactly the idea behind the package. I think a simple plot of a time series should be a recipe in the time series package(s).

**Comment by milktrader** [comment]
I'm on board with this. Plotting is integral to time series analysis but the brittle nature of plotting packages has prevented depending on them. If a simple recipe that depends on a lean package will work I'm all for it.

**Comment by mkborregaard** [comment]
Right, catch us on gitter (or here) if you need any help with the recipes :-)

**Comment by juliohm** [comment]
@milktrader please let us know when we can close this issue. Thanks.

**Comment by milktrader** [comment]
I can open an issue, reference this one and then you can close it.

**Comment by milktrader** [comment]
@juliohm I've added a list of TODO, please feel free to contribute to any of those items, preferably starting with the recipe code.

**Comment by mkborregaard** [comment]
It could be as simple as
```
using RecipesBase
@recipe f{T<:TimeArray}(ta::T) = ohlc.timestamp, ohlc.values
```
which seems to work:
```
using TimeSeries, MarketData
plot(ohlc)
```
But there are possibilities of setting more default values etc.

**Comment by mkborregaard** [comment]
You could set sensible values for legend labels with something like:
```julia
using RecipesBase, TimeSeries
@recipe function f{T<:TimeArray}(ta::T)
       labels --> reshape(ta.colnames,1,length(ta.colnames))
       seriestype --> :path
       ta.timestamp, ta.values
end

using Plots, MarketData
gr() # or whichever plotting package the user may like that has a Plots 'backend'
plot(MarketData.ohlc)
```
![defaultplot](https://cloud.githubusercontent.com/assets/8429802/22683990/b74a6a1c-ed1a-11e6-8cd9-b5c2355db2e3.png)

Note that I didn't choose the best example - as Plots already has a specialized plotting type for OHLC. Of course since it isn't a special type in MarketData there is no way to dispatch on it automatically. But you could, in this case, convert it manually:
```julia
mo = MarketData.ohlc
moplot = OHLC.([(mo.values[i,:]...) for i in 1:size(mo.values,1)])
plot(moplot)
```
![ohlcplot](https://cloud.githubusercontent.com/assets/8429802/22683994/bd2a7a44-ed1a-11e6-9c27-61baa8e886bb.png)

**Comment by mkborregaard** [comment]
@juliohm are you still meaning to contribute this recipe to TimeArrays?
@milktrader do you think `ohlc` is such an important use case that it warrants a special plotting recipe in MarketData (note that the code bit I posted currently does not have dates on the x axis)? Or is that first plot reasonable as the default for all TimeArrays?

**Comment by juliohm** [comment]
Hi @mkborregaard, I don't have time to contribute to it now, if you want to do it, please go ahead :)

Since @milktrader opened an issue in the TimeSeries repo, I am closing this one in StatPlots.

Thanks for pinging.

**Comment by milktrader** [comment]
OHLC *is* important in financial time series. The most common depiction is a candlestick with the body representing the open/close and up/down wicks representing high/low. The body will be red/green depending on whether open or close was higher.

**Comment by milktrader** [comment]
Ohlc charts years ago followed this (pattern)[https://en.m.wikipedia.org/wiki/Open-high-low-close_chart]. Another cool depiction is the ( Heikin Ashi candlesticks)[http://www.investopedia.com/articles/technical/04/092204.asp]

**Comment by mkborregaard** [comment]
There is a depiction for this already in Plots, as shown above (@tbreloff was a financial analyst, I think). Here is a zoom:
![ohlc](https://cloud.githubusercontent.com/assets/8429802/22906357/6ee91d2a-f244-11e6-9954-c9fba834acc2.png)
I think it is quite cool. The way to get this to plot automagically is to define these objects as an OHLC type in MarketData, which can then get a type recipe that simply converts it to the OHLC type in Plots. I guess this only makes sense if you want to specialize other functions on OHLC, though.
If it is a common enough usecase the user recipe could perhaps check for the names Open, Low, High and Close and do the conversion to an OHLC.

**Comment by tbreloff** [comment]
Might also be able to pass in a list of 4-tuples with seriestype = :ohlc?
(At least... that worked sometime in the past...)

**Comment by mkborregaard** [comment]
That works - that is what I did here: https://github.com/JuliaPlots/StatPlots.jl/issues/37#issuecomment-277936721
I was just wondering whether the creation of the 4-tuple could be hid under the hood.

**Comment by mkborregaard** [comment]
@milktrader you could define a recipe for candlestick using segments and boxes similar to how boxplots are built in StatPlots. It could be called with a singleton type used only for dispatch. The principle would be something like (I have cheated here by just calling boxplot)
```
type OHLCbox end
@recipe function f{T<:TimeArray}(ta::T, ::Type{OHLCbox})
              labels --> reshape(ta.colnames,1,length(ta.colnames))
              seriestype --> :boxplot
              ncol = size(ta.values,2)
              vcat([ta.timestamp for i in 1:ncol]...), vcat([ta.values[:,i] for i in 1:ncol]...)
       end

plot(MarketData.ohlc, OHLCbox)
```

**Comment by mkborregaard** [comment]
@milktrader if there are candlesticks for ohlc, is there also a special format for OHLCV?

**Comment by mkborregaard** [comment]
x-ref https://github.com/JuliaStats/TimeSeries.jl/pull/306/files

**Comment by milktrader** [comment]
No format (maybe something esoteric I haven't seen) for OHLCV
