### ISSUE TITLE
Distributions.Normal plotting is broken?

### ISSUE THREAD

**Issue by jstrube** [JuliaPlots/StatPlots.jl#54]
I'm trying to execute the example from the `README.md` (after adding the missing `using` statements):
```
using Plots
using Distributions
using StatPlots
plot(Normal(3,5), fill=(0, .5,:orange))
```
However, instead of a plot I am getting:
```
julia> plot(Normal(3,5), fill=(0, .5,:orange))
ERROR: In convertToAnyVector, could not handle the argument types: (Distributions.Normal{Float64},)
 in macro expansion at /.julia/v0.5/Plots/src/series.jl:128 [inlined]
 in apply_recipe(::Dict{Symbol,Any}, ::Type{Plots.SliceIt}, ::Distributions.Normal{Float64}, ::LinSpace{Float64}, ::Void) at /.julia/v0.5/RecipesBase/src/RecipesBase.jl:238
 in _process_userrecipes(::Plots.Plot{Plots.PyPlotBackend}, ::Dict{Symbol,Any}, ::Tuple{Distributions.Normal{Float64}}) at /.julia/v0.5/Plots/src/pipeline.jl:73
 in _plot!(::Plots.Plot{Plots.PyPlotBackend}, ::Dict{Symbol,Any}, ::Tuple{Distributions.Normal{Float64}}) at /.julia/v0.5/Plots/src/plot.jl:171
 in (::Plots.#kw##plot)(::Array{Any,1}, ::Plots.#plot, ::Distributions.Normal{Float64}) at ./<missing>:0
```
Is there a package (or another statement) that I'm missing?

**Comment by mkborregaard** [comment]
I am not sure there are any missing `using` statements. `using Plots` is not necessary (Plots is reexported by StatPlots), `using Distributions` is in the code. `using StatPlots` - well, I think it is fairly common practice when reading the examples of a given package that you can assume the package is loaded. To boot, the top of the readme still explicitly suggests `using StatPlots`.

On to the question. I cannot replicate this, it works great on my system. Is your StatPlots up to date? What Julia version are you using?

**Comment by jstrube** [comment]
I have 
StatsBase 0.15.0
StatPlots 0.3.0
Plots 0.11.2
Distributions 0.13.0

Those are the latest versions, according to the respective github pages.
```
julia> versioninfo()
Julia Version 0.5.2
Commit f4c6c9d4bb (2017-05-06 16:34 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by mkborregaard** [comment]
Strange, I can't replicate:
<img width="1219" alt="skaermbillede 2017-05-23 kl 06 37 15" src="https://cloud.githubusercontent.com/assets/8429802/26338692/5c243c2a-3f82-11e7-9900-4ab13066cac0.png">

```
julia> versioninfo()
Julia Version 0.5.2
Commit f4c6c9d4bb (2017-05-06 16:34 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```

**Comment by mkborregaard** [comment]
Could you try again? It's a bit of a mystery.

**Comment by jstrube** [comment]
Interesting. Order matters.
If I import Plots first, I have the problem.
In other words:
```
using Distributions, StatPlots
plot(Normal(3,5))
```
works.
```
using Plots, Distributions, StatPlots
plot(Normal(3,5))
```
works.
```
using Plots
using Distributions
plot(Normal(3,5))
using StatPlots
plot(Normal(3,5))
```
doesn't work.

**Comment by mkborregaard** [comment]
Huh, interesting. It is probably a niche case, as 
```
using Plots
using Distributions
# Don't attempt to plot here
using StatPlots
plot(Normal(3,5))
```
works. It has probably to do with Plots' internal way of working with "type recipes".

**Comment by mkborregaard** [comment]
Thanks for checking this!

**Comment by pkofod** [comment]
@tbreloff do you have any idea why this might be happening?

**Comment by tbreloff** [comment]
I imagine there's a method compiling a specific branch without knowledge of
the StatPlots monkeypatch, and when StatPlots is loaded it doesn't
invalidate the previously compiled method(s). Easy solution? Load StatPlots
first. ;)
