### ISSUE TITLE
Improve Distributions support

### ISSUE THREAD

**Issue by ValdarT** [JuliaPlots/StatPlots.jl#62]
It is great having support for Distributions.jl. 
Unfortunately there are some bugs. For example this works fine.
```
plot(Gamma(1, 1), fill=(0, 0.5, :skyblue), legend=false)
```
But this...
```
plot(Gamma(0.1, 1), fill=(0, 0.5, :skyblue), legend=false)
```
...works fine with plotlyjs() backend but shows an empty plot with gr() backend and something weird with pyplot() backend.

This gives an error.
```
plot(InverseGamma(2, 1), fill=(0, 0.5, :skyblue), legend=false)

ArgumentError: start and stop must be finite, got 0.0 and Inf
```
In sum, seems that Distributions support could use some attention. 

Keep up the great work!

**Comment by mkborregaard** [comment]
Thanks! If you feel adventurous, you could try to look at a fix and make a PR?

**Comment by ValdarT** [comment]
The reason for `plot(Gamma(0.1, 1)`  case seems to be that the recipe uses probability density function to get the y values...
```
@recipe function f{T<:Distribution}(::Type{T}, dist::T; func = pdf)
    xi -> func(dist, xi)
end
```
...but `pdf(Gamma(0.1, 1), 0)` is `Inf` and in general the pdf for highly skewed distributions is very large near 0 so the y axis scale gets huge. Plotly just seems to handle this internally.

I'm not sure what the proper fix should be, though. A hack would be to just add a small value to xi in the conversion
```
@recipe function f{T<:Distribution}(::Type{T}, dist::T; func = pdf)
    xi -> func(dist, xi+0.01)
end
```
but this is not a proper way to handle this.


As for `InverseGamma(2, 1)` the reason is similar - in this case `std(InverseGamma(2,1))` is `Inf` and that is used for determining the range for x axis in `default_range` function.

**Comment by mkborregaard** [comment]
Could you checkout my PR here and see if it works for you? https://github.com/JuliaPlots/StatPlots.jl/pull/66

**Comment by ValdarT** [comment]
It kind of works but not very well. 

The old version with scale limiting (doesn't work without limiting):
``` plot(Gamma(0.5,1), fill=(0,0.5), ylim=(0,3))```
![old_plot](https://user-images.githubusercontent.com/7242935/28707624-c68dc292-7381-11e7-9782-4a298995f2ad.png)

The new version (works without any limiting) does not look very nice:
``` plot(Gamma(0.5,1), fill=(0,0.5))```
![new_plot](https://user-images.githubusercontent.com/7242935/28707643-d3d829ce-7381-11e7-9de6-0063e0ff9b42.png)

I am actually surprised that your fix helped with the y-scale. Why should it make a difference to Plots whether you supply min and max vs StepRange in the same range? Perhaps the fix should actually go there instead of here?

And this does not help with the `InverseGamma(2,1)` case, of course.

**Comment by mkborregaard** [comment]
Try `Pkg.update()`.
The reason my fix should work is that the type recipe for distributions replaces the distribution with a function. When the StatPlots distribution.jl code was written, Plots would deal with functions by evaluating them over a Vector, in this case supplied by the Linspace. Today there's an adapted_grid function in PlotUtils that takes care of defining the points along the x-axis, and by supplying min and max rather than a linspace I make Plots dispatch to that function. It has been broken on julia-0.6, though, but that was fixed 2 days ago. Hence my suggestion to update.

WRT to `InverseGamma(2,1)`, the issue is that the `std` of that is `Inf`, as is the `maximum`, and thus StatPlots cannot define a range for the x axis to define the pdf over. Can you describe what you'd expect when plotting that distribution?

**Comment by mkborregaard** [comment]
BTW, note that rather than defining ylim it is better to manually define the range over which you'd like the pdf to be defined, e.g.;

```julia
plot(InverseGamma(2,1), 1/1000, 3, fill=(0, 0.5, :skyblue), legend=false)
```
![skaermbillede 2017-07-28 kl 10 39 02](https://user-images.githubusercontent.com/8429802/28709551-0ee1cec2-7381-11e7-908b-d107ca0a2da4.png)

**Comment by ValdarT** [comment]
Works like a charm with the latest Plots. Silly me for not checking the version. Thank you!
```plot(Gamma(0.5,1), fill=(0,0.5))```
![new_new_plot](https://user-images.githubusercontent.com/7242935/28712848-648e7ece-7395-11e7-83be-f0ec546f45ae.png)

> WRT to InverseGamma(2,1), the issue is that the std of that is Inf, as is the maximum, and thus StatPlots cannot define a range for the x axis to define the pdf over. Can you describe what you'd expect when plotting that distribution?

In case max is Inf take the 99-nth percentile?

``` plot(InverseGamma(2,1), 1/1000, quantile(InverseGamma(2,1), 0.99), fill=(0,0.5) ```
![new_invg99](https://user-images.githubusercontent.com/7242935/28713150-9f4334dc-7396-11e7-8b70-1cac5e3ec2a2.png)

**Comment by mkborregaard** [comment]
> In case max is Inf take the 99-nth percentile?

That makes sense, I'll have a look at that.

**Comment by mkborregaard** [comment]
I've removed the 4-standard-deviations criterion and replaced with always using the 0.01/0.99 quantile if the extrema are infinite.

**Comment by ValdarT** [comment]
Great, thanks!

**Comment by ValdarT** [comment]
Hi again

I was too hasty with my response. Although the 0.01/0.99 quantiles work well for skewed distributions they cut away too much for many distributions. The example on the front page now looks like this:
```plot(Normal(3,5), fill=(0, .5, :orange))```
![foo](https://user-images.githubusercontent.com/7242935/28868685-e19c3604-7782-11e7-941f-be797e6ef5d3.png)
In this particular case `alpha=0.0001` looks a lot better.
![foo2](https://user-images.githubusercontent.com/7242935/28868839-5f8b603a-7783-11e7-9d0e-9130a11c3fc7.png)

I think it's worth changing the default `alpha`. Skewed distributions would not look that nice anymore but it's more important to give the best result for more common cases.

**Comment by mkborregaard** [comment]
Could you make a PR
