### ISSUE TITLE
Plots export broken

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/StatPlots.jl#64]
https://github.com/JuliaPlots/StatPlots.jl/pull/50 broke Plots exports. MWE:
```julia
using StatPlots
histogram(randn(1000))
#ERROR: UndefVarError: histogram not defined
```
cc @ChrisRackauckas

**Comment by ChrisRackauckas** [comment]
Oh, I assumed like other recipes libraries one would always do `using Plots, StatPlots`. But fixing this just would require re-adding `@reexport` in front of the `using Plots`.

**Comment by mkborregaard** [comment]
No, the idea is that you shouldn't need `using Plots` but just `using StatPlots`, similar to the case for PlotRecipes - so for the user both StatPlots and PlotRecipes work like just a single plotting library. I will say though that this seems to be one of them major things that people miss when using it - and unfortunately `using Plots; plot(1:10,1:10); using StatPlots` may cause problems.
Still I'll reinstate the functionality for now.

**Comment by ChrisRackauckas** [comment]
Alright, it's easy to change it back. I think that removing it was actually a mistake anyways from when testing removing `using Plots` altogether from this repo.

**Comment by mkborregaard** [comment]
Yes I've already pushed a new release with the change :-)
