### ISSUE TITLE
Violine plot with not overlapping groups

### ISSUE THREAD

**Issue by mkrenn** [JuliaPlots/StatPlots.jl#89]
Hi!
Is there a way to create grouped violin plots on a categorical x-axis, where the violins of different groups on one category do not overlap?
Similar behavior has been discussed in #56 for boxplots, but i didn't find a solution for that.

`df = DataFrame(accuracy=Float64[],Cat1=String[],Cat2=String[])`
`for i = 1 : 100
        push!(df,[rand() rand(["A"; "B"]) rand(["1" "2" "3"])])
end`
 `violin(df,:Cat1,:accuracy,group=:Cat2,ylims=(0,1))`

![violinexample](https://user-images.githubusercontent.com/12136570/30154425-2048bb5e-93ba-11e7-964a-3bf12d66435f.png)

**Comment by mkborregaard** [comment]
Not at the moment. This is similar to `groupedbar` just for violins, and has also been requested for boxplot (https://github.com/JuliaPlots/StatPlots.jl/issues/56). It should be able to generalize that solution.

**Comment by piever** [comment]
This kind of request is being asked more and more often. Maybe it'd be good to factor all the `groupedbar` code that's needed to plot things side by side and then use it to create `groupedviolin`and `groupedboxplot`.

**Comment by mkborregaard** [comment]
👍

**Comment by mkborregaard** [comment]
Superseded by #145
